### 회원가입
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "test@test.com",
  "username": "testuser",
  "password": "testuser1234"
}

### 로그인
POST http://localhost:3000/auth/login
Content-Type: application/json

{
"email": "test@test.com",
"password": "testuser1234"
}

> {%
  client.global.set("token", response.body.accessToken);
%}
